# Generated by Django 3.0.2 on 2020-01-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_title', models.CharField(max_length=300)),
                ('ads_image', models.ImageField(upload_to='')),
                ('ads_content', models.TextField()),
                ('ads_href', models.CharField(max_length=300)),
            ],
        ),
    ]
