# Generated by Django 3.0.2 on 2020-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_image',
            field=models.ImageField(upload_to='advertisement_pics'),
        ),
    ]
